### ISSUE TITLE
[VISUAL] Updated Glow Effect

### ISSUE THREAD

**Issue by Ratatus56** [mapbase-source/source-sdk-2013#115]
### Describe alternatives you've considered
https://github.com/Facepunch/Facepunch.Highlight#facepunchhighlight
---

### Additional context
(Optional) Add any other context or screenshots about the feature request here.

**Comment by Alivebyte** [comment]
Cool feature, m8

**Comment by Blixibon** [comment]
[A Source counterpart of this feature](https://developer.valvesoftware.com/wiki/TF2_Glow_Effect_(2013_SDK)) is already implemented.

Please pay more attention to using the issue template next time as well.
