### ISSUE TITLE
Making VScript transition across levels

### ISSUE THREAD

**Issue by Blixibon** [mapbase-source/source-sdk-2013#13]
May require major refactoring of existing save/restore system.

**Comment by ReDucTor** [comment]
I think it might be worth moving this out into post-4.0 as it requires wider refactoring and his higher risk especially when it comes to load and save.

**Comment by Blixibon** [comment]
#59 adds `Save/RestoreTable` functions which can allow data to save/restore across level transitions, so I'll consider this issue closed.
