### ISSUE TITLE
[TOOLS] Couldn't load combo 208512 of shader (dyn=96)

### ISSUE THREAD

**Issue by MidnightDragons** [mapbase-source/source-sdk-2013#134]
### Describe the bug
Hammer crashes with this:
Shader 'shaders\fxc\sdk_lightmappedgeneric_ps20b.vcs' - Couldn't load combo 208512 of shader (dyn=96)

It seems like it's map-specific, cause I can open other maps. What's weird is that I've opened up Hammer on the other maps before.

### Steps to reproduce
1. Open map
2. ???
3. Crash

### Expected behavior
Hammer opens the map

**Comment by MidnightDragons** [comment]
It wasn't MapSource doing it, my bad.

**Comment by Xenthio** [comment]
mapsource lmao
