### ISSUE TITLE
[GAME] vgui_text_display cannot display text over 330 characters

### ISSUE THREAD

**Issue by mattesilk** [mapbase-source/source-sdk-2013#144]
Long text strings in the "message" keyvalue lead to unexpected blank displays. 

### Steps to reproduce

1. Have vgui_text_display in the map
2. enter a string longer than 330 characters into the "message" keyvalue
3. See error

### Expected behavior
entity should be able to handle strings of arbitrary size. Text should overflow and run off screen if resolution is too large to handle entire string. 

---

### Additional context
independent of changes to resolution, or textSize keyvalues. Add'ly changing the textAlignment does not affect reproduceability of bug.

**Comment by celisej567** [comment]
why you cant just increase this in code?
![image](https://user-images.githubusercontent.com/75926135/198839623-d699e6c7-8ac8-4ab2-a598-f71c8fa39305.png)

**Comment by Blixibon** [comment]
Increasing the string's maximum size not necessary because localization tokens can go beyond that, and Mapbase allows them to be added and used by mappers.
