### ISSUE TITLE
[TOOLS] 

### ISSUE THREAD

**Issue by RealMamitler** [mapbase-source/source-sdk-2013#153]
### Describe the bug
A clear and concise description of what the bug is:
For some reason when I set Mapbase configuration, All I see is Black. Not even the grid shows up.
The little texture preview thing shows textures, but when I switch the camera to "3D shaded  textured polygons",

I see nothing!  For some reason I cant see anything invoving a shape. I can see the axis though when I select it.
tldr: grid dont pop up, textures not being shown
Proof = (https://user-images.githubusercontent.com/68511748/139955713-c9c8e9ef-953a-4164-92f0-e63ab3e5e4f0.PNG)

### Steps to reproduce
Not sure how, but here is a list of my config configurations..
(https://user-images.githubusercontent.com/68511748/139955773-f5a8bf08-8862-4a95-bf2c-7ef9c290119c.PNG),
(https://user-images.githubusercontent.com/68511748/139955791-e934b817-9263-4e49-9e63-53e1a945d30d.PNG).

### Expected behavior:
The grid to pop up.
---

### Additional context
(Optional) Add any other context about the problem here.
I'm running hammer from The SDK 2013 source thing if that helps.

**Comment by meatspace** [comment]
Friend you most likely have missed this install step. Create a shortcut to hammer.exe then right click the shortcut and add
` -game "C:\Program Files (x86)\Steam\SteamApps\sourcemods\mapbase_episodic"`  
to the field named Target

Mine for example says `"C:\Program Files (x86)\Steam\steamapps\common\Source SDK Base 2013 Singleplayer\bin\hammer.exe" -game "C:\Program Files (x86)\Steam\SteamApps\sourcemods\mapbase_episodic"`


Alternatively you can use https://github.com/mapbase-source/source-sdk-2013/wiki/Mapbase-Multi-Tool

**Comment by RealMamitler** [comment]
Thanks!

**Comment by RealMamitler** [comment]
I was using hammer.bat for some reason, thanks though!

**Comment by RealMamitler** [comment]
Wait, I still have the problem. I still made the shortcut though?
