### ISSUE TITLE
Reactivate and fix partially-cut entities

### ISSUE THREAD

**Issue by stepa2** [mapbase-source/source-sdk-2013#16]
There are some entities in Source SDK, which are exists in code but not included into .vpc file and not compiled to .dll file:

- npc_assassin - sp/src/game/server/hl2/npc_assassin.[h/cpp]
HL2 Combine Female Assassin (model exists in HL2 Leak)
- npc_blob - sp/src/game/server/hl2/npc_blob.cpp
 Some experimental blob monster
- npc_bullsquid - sp/src/game/server/hl2/npc_bullsquid.[h/cpp] 
HL1-HL2 bullsquid (model exists in HL1 and HL2 Leak)
- npc_houndeye - sp/src/game/server/hl2/npc_houndeye.[h/cpp]
HL1-HL2 houndeye (model exists in HL1, broken in vanilla HL2 Leak)
- npc_hydra - sp/src/game/server/hl2/npc_hydra.cpp + sp/src/game/client/c_npc_hydra.cpp
HL2 Hydra monster (model exists in HL2 Leak, probably will have shader issues)
- npc_spotlight - sp/src/game/server/hl2/npc_spotlight.cpp
Spotlight with AI, fires output when player/npc is spotted (no model)
- prop_vehicle_jetski - sp/src/game/server/hl2/vehicle_jetski.cpp
Predecessor of the HL2 Airboat
- weapon_cguard - sp/src/game/server/hl2/weapon_cguard.cpp
Weapon of the cut Combine Guard (model exists in HL2 Leak)
- weapon_ar1 - sp/src/game/hl2/weapon_ar1.cpp
AK-47 cut from HL2 (model exists in HL2 Leak)
- weapon_extinguisher - sp/src/game/server/hl2/weapon_extinguisher.cpp
Extinguisher, also cut from HL2 (model also exists in HL2 Leak)
- weapon_manhack - sp/src/game/server/hl2/weapon_manhack.cpp
Just a manhack blades
- weapon_molotov - sp/src/game/server/hl2/weapon_molotov.[h/cpp]
Model exists in HL2 Leak, needs sp/src/game/server/hl2/grenade_molotov.[h/cpp] for projectile
- weapon_flaregun - sp/src/game/server/hl2/weapon_flaregun.[h/cpp]
Already fixed a bit (model exists in HL2 Leak)
- weapon_irifle - sp/src/game/server/hl2/weapon_irifle.cpp
Another flaregun, uses AR2 model
- weapon_immolator - sp/src/game/server/hl2/weapon_immolator.cpp
Cut combine flamethrower (model exists in HL2 Leak)
- weapon_sniperrifle - sp/src/game/server/hl2/weapon_sniperrifle.cpp
(model exists in HL2 Leak)
- weapon_smg2 - sp/src/game/server/hl2/weapon_smg2.cpp
Another SMG (model exists in HL2 Leak)
- weapon_thumper - sp/src/game/server/hl2/weapon_thumper.cpp
Portative Thumper (placeholder model exists in HL2 Leak)
- weapon_tripwire - sp/src/game/server/hl2/weapon_tripwire.cpp
Some tripwire (like SLAM)

Some of those entities could be fixed.

**Comment by Blixibon** [comment]
Most of these entities require additional code to get working and are not needed by most people who would use Mapbase. The models themselves also cannot be used in Mapbase alone because they come from leaks.
