### ISSUE TITLE
[VISUAL] Add _minlight (Minimum ambient light) keyvalue to func_movelinear

### ISSUE THREAD

**Issue by arbabf** [mapbase-source/source-sdk-2013#178]
Why must we be relegated to using func_door if we want a func_movelinear to always have a certain amount of light?
I don't understand why func_movelinear doesn't have this keyvalue but func_door does. Is func_movelinear that neglected? \:(

**Comment by TeamSpen210** [comment]
All brush entities support this actually, it’s just checked by VRAD during compile.

**Comment by arbabf** [comment]
Oh, okay.
