### ISSUE TITLE
[CODE] Issues compiling using the everthing makefile on Linux

### ISSUE THREAD

**Issue by TheAwesome98-Real** [mapbase-source/source-sdk-2013#194]
### Describe the bug
When compiling on Linux (and probably other POSIX OSes like macOS), there are multiple issues:
- ~~case sensitivity - Color.h is included as color.h in some files, and some windowimpostor thing~~
- ~~gcc9+support.o is never built~~
- missing symbols for discord rich presence

### Steps to reproduce
1. Generate the everything Makefile
2. make using it

### Expected behavior
It should build

### Actual behavior
It doesn't

### Additional context
(Optional) Add any other context about the problem here.

**Comment by TheAwesome98-Real** [comment]
I also tried the games Makefile and I got this error

**Comment by TheAwesome98-Real** [comment]
maybe I could undefine MAPBASE_VSCRIPT but I do want vscript support

**Comment by z33ky** [comment]
Try the "develop" branch. At least the issue with `gcc9+support.o` is fixed there.

**Comment by TheAwesome98-Real** [comment]
got error `/usr/bin/ld.gold: error: ../../devtools/gcc9+support.o: incompatible target`

not exactly sure what it means but i got it when i compiled the .o file myself using the master branch

**Comment by TheAwesome98-Real** [comment]
ah - the gcc9+support.o was compiled for x86_64 while it should've been compiled for i386

**Comment by TheAwesome98-Real** [comment]
great! i've fixed gcc9+support by adding `-m32`, but now linking fails because of missing symbols discord rich presence

**Comment by z33ky** [comment]
I've never built with Discord RPC. If you don't want it you can disable it by removing it from [sp/src/vpc_scripts/source_base.vpc:23](https://github.com/mapbase-source/source-sdk-2013/blob/264ee2b04ffd1f61132d501bc17d3b600c62ee1a/sp/src/vpc_scripts/source_base.vpc#L23).

**Comment by TheAwesome98-Real** [comment]
i would like to build with it. do i just have to link with the discord_game_sdk.so, and if so, how?

**Comment by TheAwesome98-Real** [comment]
i tried without anyway but i'm still missing the symbol `GetScriptHookManager()`
