### ISSUE TITLE
[CODE] Can't put a comma in IO System, output gets offset after restarting Hammer or map compile

### ISSUE THREAD

**Issue by 8BEATER-Il-S** [mapbase-source/source-sdk-2013#195]
### Describe the bug
The .VMF file stores wrong data about an output which contains a comma, which makes passing functions with multiple parameters through VScript quite troublesome. It's noticeable only after saving the file and restarting Hammer.
This bug also breaks logic on compile and doesn't produce any errors in compile and game consoles.
A note by another user: "Comma is used as a separator for events in old versions of Source"

### Steps to reproduce
1. Have an output which contains a comma, like this one: 
![изображение](https://user-images.githubusercontent.com/80397331/182920787-84cea077-d2d6-43f8-b638-b0e499253a79.png)
2. Restart Hammer.
3. See the parameter be transferred over to the delay and fires limit. ![изображение](https://user-images.githubusercontent.com/80397331/182921087-5a56ae68-6484-4e68-9244-b8d410fd93f7.png)

### Expected behavior
Have parameters look fine like on the first screenshot.
---

### Additional context
Possibly a Hammer or Hammer++ issue, I honestly can't verify it at this moment, but from what I've been told on Source Engine Discord, this issue is common on older versions of Source SDK.

**Comment by 8BEATER-Il-S** [comment]
![изображение](https://user-images.githubusercontent.com/80397331/182923663-71f7137a-694e-4fbf-bc6e-b0a376bf73ec.png)
It's a Hammer++ bug. Well, a feature.

**Comment by TeamSpen210** [comment]
Before either L4D2 or ASW, commas were indeed used in the VMF and BSP formats to separate outputs, so it's ambiguous as to which is which. Past that `0x1D` is used.
