### ISSUE TITLE
[VSCRIPT] CUserCmd causes the game to CTD

### ISSUE THREAD

**Issue by arbabf** [mapbase-source/source-sdk-2013#197]
### Describe the bug
Whenever accessing any method from `CUserCmd`, the game immediately crashes to desktop.

### Steps to reproduce
Steps to reproduce the behaviour:
1. Have a VScript call a `CUserCmd` function.
2. Observe the game crash to desktop.

### Expected behaviour
VScript allows me to use `CUserCmd` functions as per normal.

**Comment by samisalreadytaken** [comment]
It works fine in both 6.3 and 7.0. What does your code look like?

**Comment by arbabf** [comment]
![image](https://user-images.githubusercontent.com/34561149/184534338-a54671b5-7e31-4bb1-bdd0-015a0f8cb281.png)
Something like this. Replacing uc with CUserCmd whereever it's called results in the same effect.

**Comment by samisalreadytaken** [comment]
A usercmd cannot be manually created, the only way to access one is through the `PlayerRunCommand` hook. What you're doing is directly calling the functions of a class, not even creating an instance of it. What do you think `CBaseEntity.GetHealth()` would return?

The correct usage is the following 7.0+:
```cs
Hooks.Add( player.GetOrCreatePrivateScriptScope(), "PlayerRunCommand", function( ucmd )
{
	ucmd.SetForwardMove( 10 )
}, "" );
```

or in 6.3:
```cs
player.GetOrCreatePrivateScriptScope().PlayerRunCommand <- function()
{
	command.SetForwardMove( 10 )
}
```

**Comment by arbabf** [comment]
Ah, okay. Thanks for the help.
