### ISSUE TITLE
Hud is broken on latest Half Life 2 Build

### ISSUE THREAD

**Issue by Meccanizer** [mapbase-source/source-sdk-2013#200]
Hud is not displaying correctly on the latest build of hl2, I think the new steam deck ui update broke it. Any help on fixing this is appreciated.

Broken Hud: Note in the top left corner where my fps counter is, is where all the pickup icons are wedged into.
![image](https://user-images.githubusercontent.com/28959065/189723400-53f53054-48f6-4eef-b0be-f19e808a9b1f.png)

How hud should look
![image](https://user-images.githubusercontent.com/28959065/189723167-57616f9f-5a9c-4d62-a77b-95e88e60b6c5.png)

**Comment by THG327** [comment]
[SDK_2013_Deck.zip](https://github.com/mapbase-source/source-sdk-2013/files/9553874/SDK_2013_Deck.zip)
It's not an issue with Mapbase. For whatever reason you're not loading the hud_animations script which you can easily fix by placing the txt in the scripts directory. I have also included edited UI resource files to accommodate for the Steam Deck update by hiding things that don't work and adding UI scaling wherever possible.

**Comment by Meccanizer** [comment]
Thank you, this solved it.
