### ISSUE TITLE
[VSCRIPT] Add ViewPunch(Vector(x,y,z)) function.

### ISSUE THREAD

**Issue by celisej567** [mapbase-source/source-sdk-2013#208]
I was just minding my own business and was wondering "can I do a ViewPunch() command in VScripts? That might make some things that are awkward for me easier." I didn't find anything similar in the VScripts documentation, which means it's probably not available anywhere. The only thing I found is ScreenShake, but it's far from the same.

And I suggest adding this new function.

**Comment by TeamSpen210** [comment]
Might be a good idea to just import most of the `UTIL_*` functions, that aren't just like entity setters at least.

**Comment by Blixibon** [comment]
`ViewPunch` is already a function in `CBasePlayer`. You can use it like this:

```lua
player.ViewPunch( Vector( 0, 45, 100 ) );
```
