### ISSUE TITLE
[TOOLS] Hammer++ 3D text on vgui_text

### ISSUE THREAD

**Issue by VanderCat** [mapbase-source/source-sdk-2013#211]
### Is your feature request related to a problem? Please describe.
Hammer++ has 3D text entity `editor_text`. Perhaps it is possible to make `vgui_text` entity work with it?

### Describe the solution you'd like
As there already text code in Hammer++ i think it is matter to tinker around `.fgd` file

---

### Additional context
![img](https://ficool2.github.io/HammerPlusPlus-Website/images/features_3dtext.png)

**Comment by TeamSpen210** [comment]
That is done by the `worldtext()` helper, backported from CSGO's hammer. Adding it to Mapbase's FGDs directly would cause the regular Hammer to produce a syntax error, which isn't really desirable. It'd be better for you to add it to your own copy.

**Comment by Blixibon** [comment]
For the reasons TeamSpen outlined above, this isn't really possible without a unique Hammer++ version of the Mapbase FGDs. I'm not really interested in pursuing that at the moment, so I'll close this issue for now

**Comment by SirYodaJedi** [comment]
Bump. Hammer++ actually has an ExtendClass intended for this kind of purpose. ExtendClass is parsed last, and appends onto an already-defined fgd class (see `hammerplusplus_fgd.fgd`). As such, a `mapbase_hammerplusplus.fgd` could look very simple, like so:

```js 
@include "mapbase.fgd"

@ExtendClass worldtext() = vgui_text []
```
