### ISSUE TITLE
[VISUAL]  cutcene support

### ISSUE THREAD

**Issue by breakdowngamesYT** [mapbase-source/source-sdk-2013#215]
I would like the ability to play a video in game when its activated by a trigger in the map similar to hdtf

**Comment by Yankumo-Koishi** [comment]
I mean, maybe you can use `playvideo` command, or `logic_playmovie` entity?

**Comment by breakdowngamesYT** [comment]
thiers a command?

**Comment by breakdowngamesYT** [comment]
thank the lord
I didn't know that
I looked around online and I couldn't find anything thank you
