### ISSUE TITLE
Weapon_portalgun[MISC] 

### ISSUE THREAD

**Issue by DrPeeper228** [mapbase-source/source-sdk-2013#233]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when: i can't place portals

### Describe the solution you'd like
Copy it from Portal

### Describe alternatives you've considered
No

---

### Additional context
I am a huge portal fan, that's why i am suggesting it here

**Comment by URAKOLOUY5** [comment]
There's no legal Portal 1 source, so Mapbase never will have this

**Comment by DrPeeper228** [comment]
How so fast

**Comment by URAKOLOUY5** [comment]
Notifications, but you can also close this issue
