### ISSUE TITLE
[VISUAL] Implement actual cascaded shadow mapping

### ISSUE THREAD

**Issue by Lettuce144** [mapbase-source/source-sdk-2013#241]
### Is your feature request related to a problem? Please describe.
Kind of, the default env_global_light is buggy and ugly.

### Describe the solution you'd like
Implement CSM from this repo https://github.com/Joshua-Ashton/Source-PlusPlus
This implementation is lightweight, and will run very well on older hardware.
There is a specific commit that implements CSM, so that should make it easier to implement here.

### Describe alternatives you've considered
https://github.com/celisej567/Fake-CSM-Source-2013
A good but expensive implementation that is not really csm.

---

**Comment by URAKOLOUY5** [comment]
There is no perfect CSM in any repository, they are all bad (bad performance and render bugs).

From #44

> CSM is currently out of Mapbase's scope and the default Biohazard90 implementation has too many issues.
> 
>There's still an [env_global_light](https://developer.valvesoftware.com/wiki/Env_global_light) entity which tries to project >dynamic sunlight, although it doesn't work very well either.

and about `env_global_light` in #91

**Comment by Lettuce144** [comment]
Sorry, I didn't see that. I'll close it.
