### ISSUE TITLE
[VSCRIPT] mapspawn_addon doesn't load from VPK paths

### ISSUE THREAD

**Issue by Blixibon** [mapbase-source/source-sdk-2013#242]
### Describe the bug
`mapspawn_addon` is supposed to be loaded from every directory marked as an `addon` path in `gameinfo.txt`. This does not appear to function with VPK paths (as opposed to loose folder paths).

### Steps to reproduce
1. Have a `scripts/vscripts/mapspawn_addon.nut` file embedded in a VPK
2. Launch the game
3. See error

### Expected behavior
`mapspawn_addon.nut` should be loaded from VPKs in the same way it's loaded in loose directories.

**Comment by Petercov** [comment]
RunAddonScripts() is using Q_snprintf to concatenate file paths. It should use V_ComposeFileName instead.
