### ISSUE TITLE
[CODE] Client fails to compile.

### ISSUE THREAD

**Issue by UnknownDeveloper240** [mapbase-source/source-sdk-2013#283]
### Describe the bug
When i try to Build the solution (i am using feature/mp/develop branch)
it fails to compile the client and gives this error:
`1>libucrt.lib(hypot.obj) : error LNK2005: _hypot already defined in particles.lib(particle_sort.obj)
1>   Creating library .\Release_mod_hl2mp\\client.lib and object .\Release_mod_hl2mp\\client.exp
1>.\Release_mod_hl2mp\\client.dll : fatal error LNK1169: one or more multiply defined symbols found
1>Done building project "client_hl2mp.vcxproj" -- FAILED.`

### Steps to reproduce
1. Build the 'feature/mp/develop' or 'feature/mp/secobmod-test-1' branch
2. Wait for it to compile.
3. See error

### Expected behavior
The client should compile like the server.

**Comment by Wikot235** [comment]
Iirc, Map base MP branch is still in development, so things like that are to be expected. Personally, I would recommend temporarily using MP branch from Valve repository.

**Comment by Blixibon** [comment]
Mapbase's MP branch is not finished and not recommended for use at this time.
