### ISSUE TITLE
Vrad does not support Command line parameter 

### ISSUE THREAD

**Issue by Unusuario2** [mapbase-source/source-sdk-2013#287]
### Describe the bug
self explanatory 
![image](https://github.com/mapbase-source/source-sdk-2013/assets/110506367/1c6c0536-68ad-4a2d-871b-7cc3dd2185a6)

### Steps to reproduce
1. Add to the gameinfo.txt this code:
+    CommandLine
+    {
+        -script_dotslash_read "1"
+    }
https://github.com/mapbase-source/source-sdk-2013/pull/274
3. extecute vrad

### Expected behavior
it will show an error message

---

**Comment by Blixibon** [comment]
Can you post the `gameinfo.txt` which is producing this issue? (or at least the section including and surrounding `CommandLine`)

**Comment by Unusuario2** [comment]
Here is:`"GameInfo"
{
	game 				"Inurbs"
	title 				"Inurbs"
	title2				""
	type				singleplayer_only
	GameData			"mapbase_hl2.fgd"
	InstancePath		"maps/instances/"
	SupportsVR 			0
	SupportsXbox360 	0
	SupportsDX8			0

	CommandLine
       {
		-gamepadui //loads the new interface  	
	}

	FileSystem
	{
		SteamAppId				243730		// This sets the app ID in Steam

		SearchPaths
		{

			game+mod+mod_write+default_write_path		|gameinfo_path|.
			gamebin				|gameinfo_path|bin

			game_lv				hl2/hl2_lv.vpk
			game				|all_source_engine_paths|episodic/ep1_pak.vpk
			game				|all_source_engine_paths|hl2/hl2_textures.vpk
			game				|all_source_engine_paths|hl2/hl2_sound_misc.vpk
			game				|all_source_engine_paths|hl2/hl2_misc.vpk
			platform			|all_source_engine_paths|platform/platform_misc.vpk

			game+game_write		ep2

			gamebin				episodic/bin

			game				|all_source_engine_paths|episodic
			game				|all_source_engine_paths|hl2
			platform			|all_source_engine_paths|platform
		}
	}
}

**Comment by Blixibon** [comment]
It seems that `CommandLine` contains a key (`-gamepadui`) with no value:
```cpp
	CommandLine
	{
		-gamepadui //loads the new interface  	
	}
```
Even though a "1" technically isn't needed for this option to work on the command line, the KeyValues format requires a value for every key.
Therefore, the correct syntax would be this:
```cpp
	CommandLine
	{
		-gamepadui "1" //loads the new interface  	
	}
```
Empty quotes might work as well.

Does VRAD work after adding a value there?

**Comment by Unusuario2** [comment]
yes, now vrad works fine, thanks
