### ISSUE TITLE
[VSCRIPT] VGUI Panel's colors break once screen resolution changed.

### ISSUE THREAD

**Issue by H2xDev** [mapbase-source/source-sdk-2013#303]
### Describe the bug
Before resolution change:
![image](https://github.com/mapbase-source/source-sdk-2013/assets/7879594/5f7b29fc-4ce8-48b4-9495-5e51c784e60c)

After resolution change:
![image](https://github.com/mapbase-source/source-sdk-2013/assets/7879594/beda6751-4b66-4625-85cf-65ccf2e7c7c0)

Restart solves this problem.

### Steps to reproduce
1. Have a script that creates a vgui panel with text and so on.
2. Change resolution

### Expected behavior
The same stylized panel as before resolution change

**Comment by samisalreadytaken** [comment]
You're supposed to use `PerformLayout` callback to style your panels and their children. This is vgui's design, irrelevant to vscript.

**Comment by H2xDev** [comment]
> You're supposed to use `PerformLayout` callback to style your panels and their children. This is vgui's design, irrelevant to vscript.

I have no idea what `PerformLayout` is...

**Comment by samisalreadytaken** [comment]
https://wiki.facepunch.com/gmod/PANEL:PerformLayout

https://github.com/mapbase-source/source-sdk-2013/blob/master/sp/src/game/client/hud_hintdisplay.cpp#L172

https://github.com/samisalreadytaken/vscripts/blob/master/mapbase/steam/AchievementDisplay.nut#L298
