### ISSUE TITLE
Allow using any model as prop_static

### ISSUE THREAD

**Issue by stepa2** [mapbase-source/source-sdk-2013#31]
Fix `To use model "model.mdl" with prop_static, it must be compiled with $staticprop!`

**Comment by Blixibon** [comment]
This isn't possible. `prop_static` specifically relies on the model having a static vertex structure, which is created when the model is compiled with the `$staticprop` command.

**Comment by stepa2** [comment]
There is a [compiler](https://hl2-beta.ru/index.php?action=downloads;sa=view;down=155;language=english) with such feature.
I tried adding support of `override` key to `prop_static`, but some models (models\props_lab\labpart.mdl) became invalidly rotated.

**Comment by Blixibon** [comment]
That compiler removes the `prop_data`-imposed limitation in which only models with `allowStatic` in their prop data can become static props. Mapbase's VBSP and Slammin' Source's VBSP do this as well. Models must still be compiled with `$staticprop`.
