### ISSUE TITLE
Mabye, add Biohazard90 interpretation of CSM.

### ISSUE THREAD

**Issue by THS2121966** [mapbase-source/source-sdk-2013#44]
Cascade Shadow Mapping. 
This feature must have for mappers and game designers. And add env_cascade_light for hammer map creators.
Maybe, sorry for my English.)
https://github.com/Biohazard90/g-string_2013
https://developer.valvesoftware.com/wiki/Env_cascade_light

**Comment by Blixibon** [comment]
CSM is currently out of Mapbase's scope and the default Biohazard90 implementation has too many issues.

There's still an [`env_global_light`](https://developer.valvesoftware.com/wiki/Env_global_light) entity which tries to project dynamic sunlight, although it doesn't work very well either.
