### ISSUE TITLE
VScript no type check causes crash on invalid input

### ISSUE THREAD

**Issue by samisalreadytaken** [mapbase-source/source-sdk-2013#49]
`SquirrelVM::GetInstanceValue` needs to check the type of `hInstance` against `pExpectedType` to ensure it returns only if the types match. It could also possibly recursively check for base types too.

Recreate by passing unexpected HSCRIPT value

`player.SetOwner( 1 )`
`player.SetOwner( "" )`
`player.SetParent( 0, "" )`
`EntFireByHandle( [], "" )` etc.

**Comment by Blixibon** [comment]
Fixed in Mapbase v5.1
