### ISSUE TITLE
Add light_directional.

### ISSUE THREAD

**Issue by THS2121966** [mapbase-source/source-sdk-2013#53]
https://developer.valvesoftware.com/wiki/Light_directional
=============================================
https://github.com/THS2121966/ths_iv_engine/commit/7b09aac0fe809ae5946c0ea43d948c47e4fea3f9

**Comment by Blixibon** [comment]
Did you create this code yourself or did it come from a specific source?

**Comment by THS2121966** [comment]
I created this code based on cs go vrad logic and downfall team based improvements.

**Comment by THS2121966** [comment]
And... If you are not append any leaked content, this changes must not be applied. Sorry.

**Comment by THS2121966** [comment]
Because 90% of this code - leak...
