### ISSUE TITLE
Failed to create the solution. Missed SDK_engine_post_ps20b.fxc

### ISSUE THREAD

**Issue by THS2121966** [mapbase-source/source-sdk-2013#70]
![Снимок](https://user-images.githubusercontent.com/56027883/102459165-71d0f800-406f-11eb-927c-1e0ce2e52980.PNG)

**Comment by Blixibon** [comment]
I forgot to commit these, sorry. Fixed via an additional commit

**Comment by THS2121966** [comment]
Thanks to you for this prompt work!
