### ISSUE TITLE
[GAME] 

### ISSUE THREAD

**Issue by NICKNAME-wengreen** [mapbase-source/source-sdk-2013#97]
Can you make parallax occlusion like source 2006 or/and bump map decals or/and fix multiple reflective_glass or/and support them (RealTimeReflections) on models??

P.s. can you help me, how to use point_camera_ortho?
P.p.s. for fun ,maybe, can you make a func_cloth_phys?)

**Comment by Blixibon** [comment]
Most of these requests are impossible and/or outside of Mapbase's scope, although fixing multiple `func_reflective_glass` is on my radar.

I'm planning on making a tutorial for `point_camera_ortho` in the future.
